import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const staticAssetsPlugin = {
  name: 'static-assets-plugin',
  setup(build) {
    build.onLoad({ filter: /.+/ }, (args) => {
      return {
        watchFiles: ['styles.css', 'esbuild.config.mjs'],
      };
    });
  },
};

const prod = process.argv[2] === "production";

const buildOptions = {
  banner: {
    js: banner,
  },
  minify: prod ? true : false,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "codemirror",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "ES2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
  plugins: [
    staticAssetsPlugin,
    {
      name: 'copy-manifest-and-css',
      setup(build) {
        build.onEnd(() => {
          ['manifest.json', 'styles.css'].forEach(file => {
            const src = path.join(process.cwd(), file);
            const dest = path.join(process.cwd(), 'dist', file);
            if (fs.existsSync(src)) {
              fs.copyFileSync(src, dest);
            }
          });
        });
      },
    },
  ],
};

if (prod) {
  esbuild.build(buildOptions).catch((e) => {
    console.error(e);
    process.exit(1);
  });
} else {
  esbuild.context(buildOptions).then(ctx => ctx.watch()).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
